### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [ACBSmith/william-shakespeare_as-you-like-it#1]
Dramatis Personae:
- [x] Remove the periods after character descriptions.

- [x] Instead of using `<br/>`s for the groupings, just apply the description to all the characters like such:
```
				<li>
					<p>Amiens, lord attending on the banished duke</p>
				</li>
				<li>
					<p>Jacques, lord attending on the banished duke</p>
				</li>
```
- Note how the descriptions were changed to singular form.

- [x] The the comma after "Oliver’s house" needs to be a semicolon.

Personas:
- [x] "Jaques De Boys"  --> "Jaques de Boys"

Stage Directions:
- [x] There are multiple stage directions that need to be in their own `<tr>` element, like other "major" stage directions. The trick is that 99% of stage directions that begin with "enter" or "re-enter" are major stage directions. Check Acts 1 and 2.

- [x] There are some stage directions missing  `epub:type="z3998:stage-direction"` semantics. Check Acts 3, 4, and 5.

Songs/Verse:
- [x] Now that the songs and some verse are in `<blockquotes>`, the indents need to be adjusted. It looks like single indents need to be removed, and two indents become single indents. A song in Act 2 that looks like this:
```
							<td>
								<blockquote epub:type="z3998:song">
									<p>
										<span class="i1">Under the greenwood tree</span>
										<br/>
										<span class="i1">Who loves to lie with me,</span>
										<br/>
										<span class="i1">And turn his merry note</span>
										<br/>
										<span class="i1">Unto the sweet bird’s throat,</span>
										<br/>
										<span class="i1">Come hither, come hither, come hither:</span>
										<br/>
										<span class="i1">Here shall he see</span>
										<br/>
										<span class="i1">No enemy</span>
										<br/>
										<span class="i1">But winter and rough weather.</span>
									</p>
								</blockquote>
							</td>
```
would become this:
```
							<td>
								<blockquote epub:type="z3998:song">
									<p>
										<span>Under the greenwood tree</span>
										<br/>
										<span>Who loves to lie with me,</span>
										<br/>
										<span>And turn his merry note</span>
										<br/>
										<span>Unto the sweet bird’s throat,</span>
										<br/>
										<span>Come hither, come hither, come hither:</span>
										<br/>
										<span>Here shall he see</span>
										<br/>
										<span>No enemy</span>
										<br/>
										<span>But winter and rough weather.</span>
									</p>
								</blockquote>
							</td>
```
Act 3:
- [x] Don't apply verse semantics to both `<td>` and `<blockquote>`. Only apply it to the immediate element surrounding the verse, which would be the `<blockquote>` for "From the east to western Ind...".

- [x] OK, this is where things get tricky. This section you have verse, followed by song, interrupted by "but", followed by more song, followed by a stage direction. This is how I recommend structuring Touchstone's dialogue:
```
							<td epub:type="z3998:persona">Touchstone</td>
							<td>
								<div epub:type="z3998:verse">
									<p>
										<span>Come, sweet Audrey:</span>
										<br/>
										<span>We must be married, or we must live in bawdry.</span>
										<br/>
										<span>Farewell, good Master Oliver: not⁠—</span>
									</p>
								</div>
								<blockquote epub:type="z3998:song">
									<p>
										<span class="i1">O sweet Oliver,</span>
										<br/>
										<span class="i1">O brave Oliver,</span>
										<br/>
										<span>Leave me not behind thee:</span>
									</p>
								</blockquote>
								<p class="contiued">but⁠—</p>
								<blockquote epub:type="z3998:song">
									<p>
										<span class="i1">Wind away,</span>
										<br/>
										<span class="i1">Begone, I say,</span>
										<br/>
										<span>I will not to wedding with thee.</span>
									</p>
								</blockquote>
								<p>
									<i epub:type="z3998:stage-direction">Exeunt <b epub:type="z3998:persona">Jaques</b>, <b epub:type="z3998:persona">Touchstone</b> and <b epub:type="z3998:persona">Audrey</b>.</i>
								</p>
							</td>
```
This is very tricky stuff. If you run into situations like this, `<div>` can help but use it _sparingly_. If you want to see more instances of `<div>`s used in Shakespeare, look at Hamlet. That one was terrible!

Act 4:
- [x] In Forester's song, move the stage direction ("The rest shall bear this burden...") to the above line.

- [x] Act 4, Scene 3: There is a mixture of verse and prose. The verse is in `<blockquote>`s while the prose is outside, surrounded by `<p>`. The dialogue should look like this:
```
							<td epub:type="z3998:persona">Rosalind</td>
							<td>
								<p>She Phebes me: mark how the tyrant writes. <i epub:type="z3998:stage-direction">Reads.</i></p>
								<blockquote epub:type="z3998:verse z3998:letter">
									<p>
										<span>Art thou god to shepherd turn’d,</span>
										<br/>
										<span>That a maiden’s heart hath burn’d?</span>
									</p>
								</blockquote>
								<p class="continued">Can a woman rail thus?</p>
							</td>
```

- [x] The dialogue ( beginning with "Why, thy godhead laid apart...") is structured correctly, but the `<p>`s need the "continued" class.

Act 5:
- [x] Unlike the other songs, "It was a lover and his lass..." is not centered, therefore it does not go into a `<blockquote>` (it's stupid, but I'm trying to follow the weird formatting as closely as possible). This can indicate that Shakespeare wanted to emphasize this song. This change also occurs in A Midsummer Night's Dream. I still wonder why this is...

- [x] "Pages" in the stage direction ("Enter two Pages.") should be surrounded by `<b epub:type="z3998:persona">`.

- Make sure to run `se clean .` one more time.

**Comment by ACBSmith** [comment]
- Dramatis personae formatting came from what Alex had done with _Three Sisters_; I've changed it now
- Wherever an (exit/exeunt) or (enter) stage direction was at the end of a block of dialog (and right justified in the scans) I've made it a major stage direction.
- good heavens, I dislike having to use <div> elements in dialog
- Act 5: I've put "it was a lover and his lass" as verse and song, but removed the blockquote

**Comment by ACBSmith** [comment]
div elements in dialog, the above should read. Turns out you can actually insert a div element into a github comment.

**Comment by EmmaSweeney** [comment]
- Stage directions should not be converted. Minor stage directions stay minor stage directions and major stage directions stay major stage directions.
- I dislike using `<div>` elements too, but when you have prose, verse, and blockquotes all in one dialog section it does come in handy. This is why I couldn't look at Shakespeare for several months after completing Hamlet.

**Comment by ACBSmith** [comment]
![image](https://user-images.githubusercontent.com/19839288/120927378-9b8ee180-c6d8-11eb-970e-3653fb3914b6.png)
By converted, I mean that in the above image, I'm treating [Exit Oliver] as a minor stage direction and [Exit at the end as a major stage direction. Previously I had treated both as minor stage directions, and I can revert to that if necessary.

**Comment by ACBSmith** [comment]
[Exit Charles.], rather

**Comment by EmmaSweeney** [comment]
Please revert that. The exit at the end is a minor stage direction.

**Comment by ACBSmith** [comment]
OK, makes sense. I got a little overzealous with your note about making the [Enter] stage directions major, it would seem.

**Comment by ACBSmith** [comment]
OK, that's been reverted now. The (Enter) stage directions have been left as major stage directions.

**Comment by EmmaSweeney** [comment]
There are two lint errors. Check the dialog that starts with "Come, sweet Audrey..." in Act 3.

**Comment by ACBSmith** [comment]
That seems to have been a git error on my part, sorry. I've now committed and pushed.
